module.exports = {
    'GOOGLE_KEY': 'GOOGLE_AUTH_KEY',
    'API_BASE': 'http://localhost:3500',
    'BASE_URL': 'http://localhost:3500',
    'MOMENT_UI_DATE_FORMAT': 'DD MMM YY',
    'API_DATE_TIME_FORMAT': 'YYYY-MM-DD HH:mm:ss',
    'API_DATE_FORMAT': 'YYYY-MM-DD',
    'DATE_START_FORMAT': 'YYYY-MM-DD 00:00:00',
    'DATE_END_FORMAT': 'YYYY-MM-DD 23:59:59',
    'JWT_SECRET': 'usSKNcCHzVg0NyY8iWO9',
    'MOMENT_FULL_MONTH': 'MMMM',
    'MOMENT_HOLIDAY_FORMAT': 'ddd MMM D',
    'EARNED_LEAVE': 5,
    'OPTIONAL_HOLIDAY': 7,
    'WORK_WITHOUT_PAY': 6
}
